
--创建DBPromary数据库 
create database DBPromary
use DBPromary
go

--创建promary表

 

create table promary
(
proID int primary key,
proName nvarchar(50) not null
)

----------------------------------------------------------------------------------------------------------------------------------------
--中国34个省级行政单位 23个省 5个自治区 4个直辖市 2特别行政区
insert into promary values(1,N'北京市')
insert into promary values(2,N'天津市')
insert into promary values(3,N'上海市')
insert into promary values(4,N'重庆市')
insert into promary values(5,N'河北省')
insert into promary values(6,N'山西省')
insert into promary values(7,N'台湾省')
insert into promary values(8,N'辽宁省')
insert into promary values(9,N'吉林省')
insert into promary values(10,N'黑龙江省')
insert into promary values(11,N'江苏省')
insert into promary values(12,N'浙江省')
insert into promary values(13,N'安徽省')
insert into promary values(14,N'福建省')
insert into promary values(15,N'江西省')
insert into promary values(16,N'山东省')
insert into promary values(17,N'河南省')
insert into promary values(18,N'湖北省')
insert into promary values(19,N'湖南省')
insert into promary values(20,N'广东省')
insert into promary values(21,N'甘肃省')
insert into promary values(22,N'四川省')
--insert into promary values(23,N'山东省')
insert into promary values(24,N'贵州省')
insert into promary values(25,N'海南省')
insert into promary values(26,N'云南省')
insert into promary values(27,N'青海省')
insert into promary values(28,N'陕西省')
insert into promary values(29,N'广西壮族自治区')
insert into promary values(30,N'西藏自治区')
insert into promary values(31,N'宁夏回族自治区')
insert into promary values(32,N'新疆维吾尔自治区')
insert into promary values(33,N'内蒙古自治区')
insert into promary values(34,N'澳门特别行政区')
insert into promary values(35,N'香港特别行政区')

----------------------------------------------------------------------------------------------------------------------------------------
--创建city表
create table city
(
cityID int not null,
cityName nvarchar(50) primary key,
proID int foreign key references promary(proID)
)

----------------------------------------------------------------------------------------------------------------------------------------
--插入各个省的城市数据
--4个直辖市
insert into city values(1,N'北京市',1)
insert into city values(1,N'天津市',2)
insert into city values(1,N'上海市',3)
insert into city values(1,N'重庆市',4)
--5河北省(2005年辖：11个地级市，36个市辖区、22个县级市、108个县、6个自治县)
insert into city values(1,N'石家庄市',5)
insert into city values(2,N'唐山市',5)
insert into city values(3,N'秦皇岛市',5)
insert into city values(4,N'邯郸市',5)
insert into city values(5,N'邢台市',5)
insert into city values(6,N'保定市',5)
insert into city values(7,N'张家口市',5)
insert into city values(8,N'承德市',5)
insert into city values(9,N'沧州市',5)
insert into city values(10,N'廊坊市',5)
insert into city values(11,N'衡水市',5)
--6山西省11个城市
insert into city values(1,N'太原市',6)
insert into city values(2,N'大同市',6)
insert into city values(3,N'阳泉市',6)
insert into city values(4,N'长治市',6)
insert into city values(5,N'晋城市',6)
insert into city values(6,N'朔州市',6)
insert into city values(7,N'晋中市',6)
insert into city values(8,N'运城市',6)
insert into city values(9,N'忻州市',6)
insert into city values(10,N'临汾市',6)
insert into city values(11,N'吕梁市',6)
--7台湾省(台湾本岛和澎湖共设7市、16县，其中台北市和高雄市为“院辖市”，直属“行政院”，其余属台湾省；市下设区，县下设市（县辖市）、镇、乡，合称区市镇乡。)
insert into city values(1,N'台北市',7)
insert into city values(2,N'高雄市',7)
insert into city values(3,N'基隆市',7)
insert into city values(4,N'台中市',7)
insert into city values(5,N'台南市',7)
insert into city values(6,N'新竹市',7)
insert into city values(7,N'嘉义市',7)
insert into city values(8,N'台北县',7)
insert into city values(9,N'宜兰县',7)
insert into city values(10,N'桃园县',7)
insert into city values(11,N'新竹县',7)
insert into city values(12,N'苗栗县',7)
insert into city values(13,N'台中县',7)
insert into city values(14,N'彰化县',7)
insert into city values(15,N'南投县',7)
insert into city values(16,N'云林县',7)
insert into city values(17,N'嘉义县',7)
insert into city values(18,N'台南县',7)
insert into city values(19,N'高雄县',7)
insert into city values(20,N'屏东县',7)
insert into city values(21,N'澎湖县',7)
insert into city values(22,N'台东县',7)
insert into city values(23,N'花莲县',7)
--8辽宁省(2006年，辖：14个地级市；56个市辖区、17个县级市、19个县、8个自治县。)
insert into city values(1,N'沈阳市',8)
insert into city values(2,N'大连市',8)
insert into city values(3,N'鞍山市',8)
insert into city values(4,N'抚顺市',8)
insert into city values(5,N'本溪市',8)
insert into city values(6,N'丹东市',8)
insert into city values(7,N'锦州市',8)
insert into city values(8,N'营口市',8)
insert into city values(9,N'阜新市',8)
insert into city values(10,N'辽阳市',8)
insert into city values(11,N'盘锦市',8)
insert into city values(12,N'铁岭市',8)
insert into city values(13,N'朝阳市',8)
insert into city values(14,N'葫芦岛市',8)
--9吉林省(2006年，辖：8个地级市、1个自治州；20个市辖区、20个县级市、17个县、3个自治县。)
insert into city values(1,N'长春市',9)
insert into city values(2,N'吉林市',9)
insert into city values(3,N'四平市',9)
insert into city values(4,N'辽源市',9)
insert into city values(5,N'通化市',9)
insert into city values(6,N'白山市',9)
insert into city values(7,N'松原市',9)
insert into city values(8,N'白城市',9)
insert into city values(9,N'延边朝鲜族自治州',9)
--10黑龙江省(2006年，辖：12地级市、1地区；64市辖区、18县级市、45县、1自治县)
insert into city values(1,N'哈尔滨市',10)
insert into city values(2,N'齐齐哈尔市',10)
insert into city values(3,N'鹤 岗 市',10)
insert into city values(4,N'双鸭山市',10)
insert into city values(5,N'鸡 西 市',10)
insert into city values(6,N'大 庆 市',10)
insert into city values(7,N'伊 春 市',10)
insert into city values(8,N'牡丹江市',10)
insert into city values(9,N'佳木斯市',10)
insert into city values(10,N'七台河市',10)
insert into city values(11,N'黑 河 市',10)
insert into city values(12,N'绥 化 市',10)
insert into city values(13,N'大兴安岭地区',10)
--11江苏省(2005年辖：13个地级市；54个市辖区、27个县级市、25个县)
insert into city values(1,N'南京市',11)
insert into city values(2,N'无锡市',11)
insert into city values(3,N'徐州市',11)
insert into city values(4,N'常州市',11)
insert into city values(5,N'苏州市',11)
insert into city values(6,N'南通市',11)
insert into city values(7,N'连云港市',11)
insert into city values(8,N'淮安市',11)
insert into city values(9,N'盐城市',11)
insert into city values(10,N'扬州市',11)
insert into city values(11,N'镇江市',11)
insert into city values(12,N'泰州市',11)
insert into city values(13,N'宿迁市',11)
--12浙江省(2006年，辖：11个地级市；32个市辖区、22个县级市、35个县、1个自治县。)
insert into city values(1,N'杭州市',12)
insert into city values(2,N'宁波市',12)
insert into city values(3,N'温州市',12)
insert into city values(4,N'嘉兴市',12)
insert into city values(5,N'湖州市',12)
insert into city values(6,N'绍兴市',12)
insert into city values(7,N'金华市',12)
insert into city values(8,N'衢州市',12)
insert into city values(9,N'舟山市',12)
insert into city values(10,N'台州市',12)
insert into city values(11,N'丽水市',12)
--13安徽省(2005年辖：17个地级市；44个市辖区、5县个级市、56个县。)
insert into city values(1,N'合肥市',13)
insert into city values(2,N'芜湖市',13)
insert into city values(3,N'蚌埠市',13)
insert into city values(4,N'淮南市',13)
insert into city values(5,N'马鞍山市',13)
insert into city values(6,N'淮北市',13)
insert into city values(7,N'铜陵市',13)
insert into city values(8,N'安庆市',13)
insert into city values(9,N'黄山市',13)
insert into city values(10,N'滁州市',13)
insert into city values(11,N'阜阳市',13)
insert into city values(12,N'宿州市',13)
insert into city values(13,N'巢湖市',13)
insert into city values(14,N'六安市',13)
insert into city values(15,N'亳州市',13)
insert into city values(16,N'池州市',13)
insert into city values(17,N'宣城市',13)
--14福建省(2006年辖：9个地级市；26个市辖区、14个县级市、45个县。)
insert into city values(1,N'福州市',14)
insert into city values(2,N'厦门市',14)
insert into city values(3,N'莆田市',14)
insert into city values(4,N'三明市',14)
insert into city values(5,N'泉州市',14)
insert into city values(6,N'漳州市',14)
insert into city values(7,N'南平市',14)
insert into city values(8,N'龙岩市',14)
insert into city values(9,N'宁德市',14)
--15江西省(2006年全省辖：11个地级市；19个市辖区、10个县级市、70个县。)
insert into city values(1,N'南昌市',15)
insert into city values(2,N'景德镇市',15)
insert into city values(3,N'萍乡市',15)
insert into city values(4,N'九江市',15)
insert into city values(5,N'新余市',15)
insert into city values(6,N'鹰潭市',15)
insert into city values(7,N'赣州市',15)
insert into city values(8,N'吉安市',15)
insert into city values(9,N'宜春市',15)
insert into city values(10,N'抚州市',15)
insert into city values(11,N'上饶市',15)
--16山东省(2005年，辖：17个地级市；49个市辖区、31个县级市、60个县。)
insert into city values(1,N'济南市',16)
insert into city values(2,N'青岛市',16)
insert into city values(3,N'淄博市',16)
insert into city values(4,N'枣庄市',16)
insert into city values(5,N'东营市',16)
insert into city values(6,N'烟台市',16)
insert into city values(7,N'潍坊市',16)
insert into city values(8,N'济宁市',16)
insert into city values(9,N'泰安市',16)
insert into city values(10,N'威海市',16)
insert into city values(11,N'日照市',16)
insert into city values(12,N'莱芜市',16)
insert into city values(13,N'临沂市',16)
insert into city values(14,N'德州市',16)
insert into city values(15,N'聊城市',16)
insert into city values(16,N'滨州市',16)
insert into city values(17,N'菏泽市',16)
--17河南省（2005年辖：17个地级市；50个市辖区、21个县级市、88个县。）
insert into city values(1,N'郑州市',17)
insert into city values(2,N'开封市',17)
insert into city values(3,N'洛阳市',17)
insert into city values(4,N'平顶山市',17)
insert into city values(5,N'安阳市',17)
insert into city values(6,N'鹤壁市',17)
insert into city values(7,N'新乡市',17)
insert into city values(8,N'焦作市',17)
insert into city values(9,N'濮阳市',17)
insert into city values(10,N'许昌市',17)
insert into city values(11,N'漯河市',17)
insert into city values(12,N'三门峡市',17)
insert into city values(13,N'南阳市',17)
insert into city values(14,N'商丘市',17)
insert into city values(15,N'信阳市',17)
insert into city values(16,N'周口市',17)
insert into city values(17,N'驻马店市',17)
insert into city values(18,N'济源市',17)
--18湖北省（截至2005年12月31日，全省辖13个地级单位（12个地级市、1个自治州）；102县级单位（38个市辖区、24个县级市、37个县、2个自治县、1个林区），共有1220个乡级单位（277个街道、733个镇、210个乡）。）
insert into city values(1,N'武汉市',18)
insert into city values(2,N'黄石市',18)
insert into city values(3,N'十堰市',18)
insert into city values(4,N'荆州市',18)
insert into city values(5,N'宜昌市',18)
insert into city values(6,N'襄樊市',18)
insert into city values(7,N'鄂州市',18)
insert into city values(8,N'荆门市',18)
insert into city values(9,N'孝感市',18)
insert into city values(10,N'黄冈市',18)
insert into city values(11,N'咸宁市',18)
insert into city values(12,N'随州市',18)
insert into city values(13,N'仙桃市',18)
insert into city values(14,N'天门市',18)
insert into city values(15,N'潜江市',18)
insert into city values(16,N'神农架林区',18)
insert into city values(17,N'恩施土家族苗族自治州',18)
--19湖南省（2005年辖：13个地级市、1个自治州；34个市辖区、16个县级市、65个县、7个自治县。）
insert into city values(1,N'长沙市',19)
insert into city values(2,N'株洲市',19)
insert into city values(3,N'湘潭市',19)
insert into city values(4,N'衡阳市',19)
insert into city values(5,N'邵阳市',19)
insert into city values(6,N'岳阳市',19)
insert into city values(7,N'常德市',19)
insert into city values(8,N'张家界市',19)
insert into city values(9,N'益阳市',19)
insert into city values(10,N'郴州市',19)
insert into city values(11,N'永州市',19)
insert into city values(12,N'怀化市',19)
insert into city values(13,N'娄底市',19)
insert into city values(14,N'湘西土家族苗族自治州',19)
--20广东省（截至2005年12月31日，广东省辖：21个地级市，54个市辖区、23个县级市、41个县、3个自治县，429个街道办事处、1145个镇、4个乡、7个民族乡。）
insert into city values(1,N'广州市',20)
insert into city values(2,N'深圳市',20)
insert into city values(3,N'珠海市',20)
insert into city values(4,N'汕头市',20)
insert into city values(5,N'韶关市',20)
insert into city values(6,N'佛山市',20)
insert into city values(7,N'江门市',20)
insert into city values(8,N'湛江市',20)
insert into city values(9,N'茂名市',20)
insert into city values(10,N'肇庆市',20)
insert into city values(11,N'惠州市',20)
insert into city values(12,N'梅州市',20)
insert into city values(13,N'汕尾市',20)
insert into city values(14,N'河源市',20)
insert into city values(15,N'阳江市',20)
insert into city values(16,N'清远市',20)
insert into city values(17,N'东莞市',20)
insert into city values(18,N'中山市',20)
insert into city values(19,N'潮州市',20)
insert into city values(20,N'揭阳市',20)
insert into city values(21,N'云浮市',20)
--21甘肃省（2006年辖：12个地级市、2个自治州；17个市辖区、4个县级市、58个县、7个自治县。）
insert into city values(1,N'兰州市',21)
insert into city values(2,N'金昌市',21)
insert into city values(3,N'白银市',21)
insert into city values(4,N'天水市',21)
insert into city values(5,N'嘉峪关市',21)
insert into city values(6,N'武威市',21)
insert into city values(7,N'张掖市',21)
insert into city values(8,N'平凉市',21)
insert into city values(9,N'酒泉市',21)
insert into city values(10,N'庆阳市',21)
insert into city values(11,N'定西市',21)
insert into city values(12,N'陇南市',21)
insert into city values(13,N'临夏回族自治州',21)
insert into city values(14,N'甘南藏族自治州',21)
--22四川省（2006年辖：18个地级市、3个自治州；43个市辖区、14个县级市、120个县、4个自治县。）
insert into city values(1,N'成都市',22)
insert into city values(2,N'自贡市',22)
insert into city values(3,N'攀枝花市',22)
insert into city values(4,N'泸州市',22)
insert into city values(5,N'德阳市',22)
insert into city values(6,N'绵阳市',22)
insert into city values(7,N'广元市',22)
insert into city values(8,N'遂宁市',22)
insert into city values(9,N'内江市',22)
insert into city values(10,N'乐山市',22)
insert into city values(11,N'南充市',22)
insert into city values(12,N'眉山市',22)
insert into city values(13,N'宜宾市',22)
insert into city values(14,N'广安市',22)
insert into city values(15,N'达州市',22)
insert into city values(16,N'雅安市',22)
insert into city values(17,N'巴中市',22)
insert into city values(18,N'资阳市',22)
insert into city values(19,N'阿坝藏族羌族自治州',22)
insert into city values(20,N'甘孜藏族自治州',22)
insert into city values(21,N'凉山彝族自治州',22)
/**//****************************************
--23山东省(2005年，辖：17个地级市；49个市辖区、31个县级市、60个县。)
insert into city values(1,N'济南市',16)
insert into city values(2,N'青岛市',16)
insert into city values(3,N'淄博市',16)
insert into city values(4,N'枣庄市',16)
insert into city values(5,N'东营市',16)
insert into city values(6,N'烟台市',16)
insert into city values(7,N'潍坊市',16)
insert into city values(8,N'济宁市',16)
insert into city values(9,N'泰安市',16)
insert into city values(10,N'威海市',16)
insert into city values(11,N'日照市',16)
insert into city values(12,N'莱芜市',16)
insert into city values(13,N'临沂市',16)
insert into city values(14,N'德州市',16)
insert into city values(15,N'聊城市',16)
insert into city values(16,N'滨州市',16)
insert into city values(17,N'菏泽市',16)
*************************************/
--24贵州省(2006年辖：4个地级市、2个地区、3个自治州；10个市辖区、9个县级市、56个县、11个自治县、2个特区。)
insert into city values(1,N'贵阳市',24)
insert into city values(2,N'六盘水市',24)
insert into city values(3,N'遵义市',24)
insert into city values(4,N'安顺市',24)
insert into city values(5,N'铜仁地区',24)
insert into city values(6,N'毕节地区',24)
insert into city values(7,N'黔西南布依族苗族自治州',24)
insert into city values(8,N'黔东南苗族侗族自治州',24)
insert into city values(9,N'黔南布依族苗族自治州',24)
--25海南省(2003－2005年　全省有2个地级市，6个县级市，4个县，6个民族自治县，4个市辖区，1个办事处（西南中沙群岛办事处，县级）。)
insert into city values(1,N'海口市',25)
insert into city values(2,N'三亚市',25)
insert into city values(3,N'五指山市',25)
insert into city values(4,N'琼海市',25)
insert into city values(5,N'儋州市',25)
insert into city values(6,N'文昌市',25)
insert into city values(7,N'万宁市',25)
insert into city values(8,N'东方市',25)
insert into city values(9,N'澄迈县',25)
insert into city values(10,N'定安县',25)
insert into city values(11,N'屯昌县',25)
insert into city values(12,N'临高县',25)
insert into city values(13,N'白沙黎族自治县',25)
insert into city values(14,N'昌江黎族自治县',25)
insert into city values(15,N'乐东黎族自治县',25)
insert into city values(16,N'陵水黎族自治县',25)
insert into city values(17,N'保亭黎族苗族自治县',25)
insert into city values(18,N'琼中黎族苗族自治县',25)
--26云南省(2006年辖：8个地级市、8个自治州；12个市辖区、9个县级市、79个县、29个自治县。)
insert into city values(1,N'昆明市',26)
insert into city values(2,N'曲靖市',26)
insert into city values(3,N'玉溪市',26)
insert into city values(4,N'保山市',26)
insert into city values(5,N'昭通市',26)
insert into city values(6,N'丽江市',26)
insert into city values(7,N'思茅市',26)
insert into city values(8,N'临沧市',26)
insert into city values(9,N'文山壮族苗族自治州',26)
insert into city values(10,N'红河哈尼族彝族自治州',26)
insert into city values(11,N'西双版纳傣族自治州',26)
insert into city values(12,N'楚雄彝族自治州',26)
insert into city values(13,N'大理白族自治州',26)
insert into city values(14,N'德宏傣族景颇族自治州',26)
insert into city values(15,N'怒江傈傈族自治州',26)
insert into city values(16,N'迪庆藏族自治州',26)
--27青海省(2006年辖：1个地级市、1个地区、6个自治州；4个市辖区、2个县级市、30个县、7个自治县。)
insert into city values(1,N'西宁市',27)
insert into city values(2,N'海东地区',27)
insert into city values(3,N'海北藏族自治州',27)
insert into city values(4,N'黄南藏族自治州',27)
insert into city values(5,N'海南藏族自治州',27)
insert into city values(6,N'果洛藏族自治州',27)
insert into city values(7,N'玉树藏族自治州',27)
insert into city values(8,N'海西蒙古族藏族自治州',27)
--28陕西省(2006年辖：10个地级市；24个市辖区、3个县级市、80个县。)
insert into city values(1,N'西安市',28)
insert into city values(2,N'铜川市',28)
insert into city values(3,N'宝鸡市',28)
insert into city values(4,N'咸阳市',28)
insert into city values(5,N'渭南市',28)
insert into city values(6,N'延安市',28)
insert into city values(7,N'汉中市',28)
insert into city values(8,N'榆林市',28)
insert into city values(9,N'安康市',28)
insert into city values(10,N'商洛市',28)
--29广西壮族自治区(2005年辖：14个地级市；34个市辖区、7个县级市、56个县、12个自治县。)
insert into city values(1,N'南宁市',29)
insert into city values(2,N'柳州市',29)
insert into city values(3,N'桂林市',29)
insert into city values(4,N'梧州市',29)
insert into city values(5,N'北海市',29)
insert into city values(6,N'防城港市',29)
insert into city values(7,N'钦州市',29)
insert into city values(8,N'贵港市',29)
insert into city values(9,N'玉林市',29)
insert into city values(10,N'百色市',29)
insert into city values(11,N'贺州市',29)
insert into city values(12,N'河池市',29)
insert into city values(13,N'来宾市',29)
insert into city values(14,N'崇左市',29)
--30西藏自治区(2005年辖：1个地级市、6个地区；1个市辖区、1个县级市、71个县。)
insert into city values(1,N'拉萨市',30)
insert into city values(2,N'那曲地区',30)
insert into city values(3,N'昌都地区',30)
insert into city values(4,N'山南地区',30)
insert into city values(5,N'日喀则地区',30)
insert into city values(6,N'阿里地区',30)
insert into city values(7,N'林芝地区',30)
--31宁夏回族自治区
insert into city values(1,N'银川市',31)
insert into city values(2,N'石嘴山市',31)
insert into city values(3,N'吴忠市',31)
insert into city values(4,N'固原市',31)
insert into city values(5,N'中卫市',31)
--32新疆维吾尔自治区(2005年辖：2个地级市、7个地区、5个自治州；11个市辖区、20个县级市、62个县、6个自治县)
insert into city values(1,N'乌鲁木齐市',32)
insert into city values(2,N'克拉玛依市',32)
insert into city values(3,N'石河子市　',32)
insert into city values(4,N'阿拉尔市',32)
insert into city values(5,N'图木舒克市',32)
insert into city values(6,N'五家渠市',32)
insert into city values(7,N'吐鲁番市',32)
insert into city values(8,N'阿克苏市',32)
insert into city values(9,N'喀什市',32)
insert into city values(10,N'哈密市',32)
insert into city values(11,N'和田市',32)
insert into city values(12,N'阿图什市',32)
insert into city values(13,N'库尔勒市',32)
insert into city values(14,N'昌吉市',32)
insert into city values(15,N'阜康市',32)
insert into city values(16,N'米泉市',32)
insert into city values(17,N'博乐市',32)
insert into city values(18,N'伊宁市',32)
insert into city values(19,N'奎屯市',32)
insert into city values(20,N'塔城市',32)
insert into city values(21,N'乌苏市',32)
insert into city values(22,N'阿勒泰市',32)
--33内蒙古自治区(2006年，辖：9个地级市、3个盟；21个市辖区、11个县级市、17个县、49个旗、3个自治旗。)
insert into city values(1,N'呼和浩特市',33)
insert into city values(2,N'包头市',33)
insert into city values(3,N'乌海市',33)
insert into city values(4,N'赤峰市',33)
insert into city values(5,N'通辽市',33)
insert into city values(6,N'鄂尔多斯市',33)
insert into city values(7,N'呼伦贝尔市',33)
insert into city values(8,N'巴彦淖尔市',33)
insert into city values(9,N'乌兰察布市',33)
insert into city values(10,N'锡林郭勒盟',33)
insert into city values(11,N'兴安盟',33)
insert into city values(12,N'阿拉善盟',33)
--34澳门特别行政区
insert into city values(1,N'澳门特别行政区',34)
--35香港特别行政区
insert into city values(1,N'香港特别行政区',35)

----------------------------------------------------------------------------------------------------------------------------------------
